### ISSUE TITLE
Structure the site's visual layout

### ISSUE THREAD

**Issue by briancmlee** [MHSDevClub/MHSDevClub.github.io#1]
Create the visual site structure as in [Low-Fidelity Wireframe](https://www.figma.com/file/bJ6dX6nI5Q6CbvhZ6LDhDKKN/Low-Fidelity-Wireframe) with CSS.

**DO NOT** structure the visual layout and use filler divs for:
* Header
* Sign Up Form
* Sign Up Modal Window
* Projects gallery items
* Summary section
* Footer

Code mobile-first by creating the mobile layout and extending to larger screens with media queries. You *can* use CSS Frameworks if it helps you create layout faster, but try to keep HTML as symantic as possible.

**Comment by emilytrau** [comment]
Decided that a global grid structure is not required. Structure will instead be managed inside each component's style.
